name: Save Done Issues as Markdown and Create PR

on:
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  save_issues:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Save Issues
      env:
        GITHUB_TOKEN: ${{ secrets.issuetomd1 }}
      run: |
        python save_issues.py

    - name: Create a new branch
      run: |
        git checkout -b update-markdown-${{ github.run_id }}

    # Add all new and modified files to Git's tracking system, including images
    - name: Add changes
      run: |
        git add -A

    # Commit the changes, handle the case where there are no changes
    - name: Commit changes
      run: |
        git config --global user.name 'stevefaulkner'
        git config --global user.email 'faulkner.steve@gmail.com'
        git commit -m "Update Markdown files for issues labeled as done" || echo "No changes to commit"

    # Push the changes to the new branch
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.issuetomd1 }}
        branch: update-markdown-${{ github.run_id }}

    # Create a Pull Request from the new branch to the main branch
    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.issuetomd1 }}
        pr_title: "Update Markdown files for issues labeled as done"
        pr_body: "This PR updates the Markdown files for issues labeled as done."
        source_branch: update-markdown-${{ github.run_id }}
        destination_branch: "main"  # Ensure this is your target branch for PRs
