name: Save Done Issues as Markdown and Create PR

on:
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  save_issues:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Save Issues
      env:
        GITHUB_TOKEN: ${{ secrets.issuetomd1 }}
      run: |
        python save_issues.py

    - name: Create a new branch
      run: |
        git checkout -b update-markdown-${{ github.run_id }}

    - name: Check for changes
      id: check_changes
      run: |
        git status
        if git diff --quiet; then
          echo "No changes to commit."
          echo "::set-output name=changes::false"
        else
          echo "::set-output name=changes::true"
        fi

    - name: Commit files
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --global user.name 'stevefaulkner'
        git config --global user.email 'faulkner.steve@gmail.com'
        git add -A
        git commit -m "Update Markdown files for issues labeled as done"

    - name: Push changes
      if: steps.check_changes.outputs.changes == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.issuetomd1 }}
        branch: update-markdown-${{ github.run_id }}

    - name: Create Pull Request
      if: steps.check_changes.outputs.changes == 'true'
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.issuetomd1 }}
        pr_title: "Update Markdown files for issues labeled as done"
        pr_body: "This PR updates the Markdown files for issues labeled as done."
        destination_branch: "main"  # Change this to your default branch if it's not 'main'


 
